services:
  api:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://flag:flagpass@db:5432/flagdb
      # CORS ya no importa, pero puedes dejarlo
      - CORS_ORIGINS=http://localhost:8080,http://sidedominicana.com:8080,https://sidedominicana.com
    expose:
      - "3000"           # expuesto a la red interna; (opcional) ports si lo quieres fuera
    depends_on:
      - db

  web:
    build:
      context: ./flag-team-web
    ports:
      - "8080:80"        # la web pública queda en :8080
    depends_on:
      - api
    # Nginx hablará con 'api:3000' por red interna de compose

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=flag
      - POSTGRES_PASSWORD=flagpass
      - POSTGRES_DB=flagdb
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
